/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor */

#ifndef _Included_com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor
#define _Included_com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor
 * Method:    loogcollectorStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor_loogcollectorStart
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor
 * Method:    loogcollectorStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shsnc_agent_ivory_plugin_loongcollector_LoongCollectorProcessor_loogcollectorStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
