/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin */

#ifndef _Included_com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin
#define _Included_com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin
 * Method:    loogcollectorStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin_loogcollectorStart
  (JNIEnv *, jclass);

/*
 * Class:     com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin
 * Method:    loogcollectorStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shsnc_agent_plugin_loongcollector_LoongcollectorPlugin_loogcollectorStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
